#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")

if [ "$STAGED_FILES" = "" ]; then
    exit 0
fi

PASS=true

echo "\nValidating PHP-Lint and PHPCS:\n"

# Check for parallel-lint
which ./vendor/bin/parallel-lint &> /dev/null
if [ "$?" = 1 ]; then
    echo "\t\033[41mPlease install PHP-Parallel-Lint\033[0m"
    exit 1
fi

# Check for phpcs
which ./vendor/bin/phpcs &> /dev/null
if [ "$?" = 1 ]; then
    echo "\t\033[41mPlease install PHPCS\033[0m"
    exit 1
fi

RULESET=./phpcs.xml

echo "\n\033[34m===================================================================\033[0m"
echo "\033[34m===================== Checking with PHP-Lint: =====================\033[0m"
echo "\033[34m===================================================================\033[0m \n"

for FILE in $STAGED_FILES
do
    ./vendor/bin/parallel-lint --exclude vendor --exclude storage --exclude resources --exclude node_modules "$FILE"

    if [ "$?" = 0 ]; then
        echo "\t\033[32mPHP-Lint Passed: $FILE\033[0m"
    else
        echo "\t\033[41mPHP-Lint Failed: $FILE\033[0m"
        PASS=false
    fi
done

echo "\n\033[34m===================================================================\033[0m"
echo "\033[34m======================= Checking with PHPCS: ======================\033[0m"
echo "\033[34m===================================================================\033[0m \n"

for FILE in $STAGED_FILES
do
    ./vendor/bin/phpcs --standard="$RULESET" "$FILE"

    if [ "$?" = 0 ]; then
        echo "\t\033[32mPHPCS Passed: $FILE\033[0m"
    else
        echo "\t\033[41mPHPCS Failed: $FILE\033[0m"
        PASS=false
    fi
done

echo "\n\033[34m===================================================================\033[0m"
echo "\033[34m======== PHP-Parallel-Lint and PHPCS validation completed!: =======\033[0m"
echo "\033[34m===================================================================\033[0m \n"

if ! $PASS; then
    echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass PHP-Parallel-Lint and PHPCS but do not. Please fix the PHP-Parallel-Lint and PHPCS errors and try again.\n"
    exit 1
else
    echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?
